<?php

/**
 * @var \Cowell\BasicTraining\Block\Index $block
 */

$student_detail = $block->getStudent();
?>
<div class="box box-information">
    <strong class="box-title">
        <span>Student Information</span>
    </strong>
    <div class="box-content">
        <ul>
            <li><p>ID: <?= $student_detail['id'] ?> </p></li>
            <li><p>Name: <?= $student_detail['name'] ?> </p></li>
            <li><p>Date of birth: <?= $student_detail['dob'] ?> </p></li>
            <li><p>Gender: <?= $student_detail['gender'] ?> </p></li>
            <li><p>Address: <?= $student_detail['address'] ?> </p></li>
            <li><p>Created at: <?= $student_detail['created_at'] ?> </p></li>
            <li><p>Updated at: <?= $student_detail['updated_at'] ?> </p></li>
        </ul>
    </div>
    <div class="box-actions">
        <a class="action edit" href="#">
            <span>Edit</span>
        </a>
    </div>
</div>
