<?php

/**
 * @var \Cowell\BasicTraining\Block\Student $block
 */
$viewModel = $block->getStudent();
$listStudent = $viewModel->getAllStudent();
//$listStudent = $block->getAllStudent();
$gender = $this->getRequest()->getParam('gender');
?>
<form action="" method="get">
    <label for="">Sort by ID:</label>
    <select name="id" id="" style="width: 70px">
        <option value="ASC">ASC</option>
        <option value="DESC">DESC</option>
    </select>
    <label for="" style="margin-left: 20px"> Name:</label>
    <input type="text" style="width: 160px" name="key" value="<?php echo $this->getRequest()->getParam('key') ?>">
    <label for="" style="margin-left: 20px">Gender:</label>
    <select name="gender" id="" style="width: 90px">
        <option value="">All</option>
        <option value="1" <?php if ($gender == '1') {
    echo 'selected';
} ?> >Male
        </option>
        <option value="0" <?php if ($gender == '0') {
    echo 'selected';
} ?> >Female
        </option>
    </select>
    <label for="" style="margin-left: 20px">From:</label>
    <input type="date" name="start" style="width: 130px" value="<?php echo $this->getRequest()->getParam('start') ?>">
    <label for="" style="margin-left: 10px">To:</label>
    <input type="date" name="end" style="width: 130px" value="<?php echo $this->getRequest()->getParam('end') ?>">
    <button type="submit" style="margin-top: -3px" class="action subscribe primary">Submit</button>
</form>

<table style="margin-top: 30px" class="data table table-order-items recent">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Gender</th>
        <th>Date of birth</th>
        <th>*</th>
    </tr>
    <?php foreach ($listStudent as $student) { ?>

        <tr>
            <td><?= $student->getID() ?></td>
            <td><?= $student->getName() ?></td>
            <td>
                <?php
                $gender = $student->getGender();
                if ($gender == 1) {
                    echo 'Male';
                } else {
                    echo 'Female';
                }
                ?>
            </td>
            <td><?= $student->getDob() ?></td>
            <td><a href="<?= $block->getUrl('sinh-vien') . $student->getID(); ?>">View</a></td>
        </tr>
    <?php } ?>
</table>

<?php if ($block->getPagerHtml()): ?>
    <div class="order-products-toolbar toolbar bottom" style="margin-top: 30px">
        <?php echo $block->getPagerHtml(); ?>
    </div>
<?php endif ?>
